### ISSUE TITLE
Autoheight Components

### ISSUE THREAD

**Issue by deepak-jha-kgp** [HishamMubarak/react-native-math#1]
Hey! Thank you for this library. 
I was wondering is there any way we can auto-height these components?

**Comment by HishamMubarak** [comment]
> Hey! Thank you for this library.
> I was wondering is there any way we can auto-height these components?

I don't think that is possible. Because, under the hood, it uses native Android WebView to render the math content. WebView needs to have a specific height set to it, as it cannot resize to the html/math content provided to it. Two supported height options are either using flex or using the minHeight style property to set the height for the math Component.

**Comment by deepak-jha-kgp** [comment]
We do have a library for autoheight webviews in react native. Check this out 
https://www.npmjs.com/package/react-native-webview-autoheight
I'm not very sure about Android Webview, but I guess there should be a way around. And even if there isn't, how about we implement react-native autoheight webview instead of android webview?

**Comment by HishamMubarak** [comment]
@deepak-jha-kgp , will definitely check it out and see what I can do.

**Comment by deepak-jha-kgp** [comment]
Any updates on this? Did you get a chance to look at it @HishamMubarak ?

**Comment by HishamMubarak** [comment]
> Any updates on this? Do you get a chance to look at it @HishamMubarak ?

Haven't had a chance yet to take a look at it.

**Comment by deepak-jha-kgp** [comment]
Hey @HishamMubarak , will you looking into this?

**Comment by HishamMubarak** [comment]
> Hey @HishamMubarak , will you looking into this?

Hi, I did look into it a while ago. Right now, the android katex library is using a native android webview and not the React native webview. For yourr requirement, will have to remove the android katex library, load RN webview you mentioned earlier and set up things. With the current syntax, I think things might break. Will have to try and see how it goes and if it works well, will need to release a major version update.

**Comment by HishamMubarak** [comment]
Added autoheight support and iOS support in #3 
Update package version to 2.0.0 or higher to enable them

**Comment by HishamMubarak** [comment]
Added autoheight support and iOS support in #3 
Update package version to 2.0.0 or higher to enable them
