### ISSUE TITLE
error: Error: Unable to resolve module ../types from node_modules/react-native-math/dist/index.js: 

### ISSUE THREAD

**Issue by pzj6124** [HishamMubarak/react-native-math#6]
"react-native-math": "^2.0.0"
"react": "18.1.0",
"react-native": "0.70.8"

![image](https://github.com/user-attachments/assets/112a4281-a7db-4b1a-9af1-10ff3b24f29f)

**Comment by HishamMubarak** [comment]
Fixed in version 2.0.1
