### ISSUE TITLE
Add support for Expo

### ISSUE THREAD

**Issue by anasvemmully** [HishamMubarak/react-native-math#9]

**Comment by giulianoo0** [comment]
It supports Expo perfectly, just install `react-native-webview` through it's manager (`npx expo install react-native-webview`).
What problem are you experiencing?

**Comment by anasvemmully** [comment]
Oh ok, I thought while `npm i react-native-math` and using everything should be fine. but instead for me the issue was having multiple version of `react-native-webview` and causing error. let me check, I appreciate your insights.
